### PR TITLE
Add {{ hook }} template variable

### PR DESCRIPTION
**Pull request by markcarver**
Pretty simple PR, but would be nice to have the ability to determine what the current hook is if there are multiple hooks sharing the same template.

### CODE REVIEW

**Comment by franz-josef-kaiser** [comment]
Looking good for me. Thanks for the PR _with_ an updated README!

**Comment by markcarver** [comment]
@franz-josef-kaiser, any chance this can get released??

**Comment by franz-josef-kaiser** [comment]
@markcarver Sry, I somehow completely missed moving further. Thanks for your PR!

**Comment by markcarver** [comment]
Release/tag, whatever will update https://www.npmjs.com/package/grunt-githooks and allow me to specify the newer version in my grunt setup.

**Comment by franz-josef-kaiser** [comment]
@markcarver [Available as `0.5.0`](https://www.npmjs.com/package/grunt-githooks)

**Comment by markcarver** [comment]
:smiley: thanks!!

**Pull request merged**
